import { UserId } from '@common/domain/value-objects/user-id.vo';
import {
	BadRequestException,
	Inject,
	Injectable,
	NotFoundException,
} from '@nestjs/common';
import { UserResourcesMapper } from '@users/application/mappers/user-resources.mapper';
import {
	ISavedPagesRepository,
	I_SAVED_PAGES_REPOSITORY,
} from '@users/application/ports/saved-pages-repository.interface';
import {
	SavedPage,
	SavedPageSnapshot,
} from '@users/domain/entities/saved-page';
import { CreateSavedPageDto } from '@users/infrastructure/http/dto/create-saved-page.dto';
import { UpdateSavedPageDto } from '@users/infrastructure/http/dto/update-saved-page.dto';

@Injectable()
export class SavedPagesService {
	constructor(
		@Inject(I_SAVED_PAGES_REPOSITORY)
		private readonly savedPagesRepository: ISavedPagesRepository,
		private readonly userResourcesMapper: UserResourcesMapper,
	) {}

	/**
	 * Salva uma página para o usuário
	 */
	async savePage(
		dto: CreateSavedPageDto,
		userIdStr: string,
	): Promise<SavedPageSnapshot> {
		const userId = UserId.create(userIdStr);

		// Verifica se a página existe e pertence ao capítulo/livro informado
		const isOwnershipValid =
			await this.savedPagesRepository.verifyPageOwnership(
				dto.pageId,
				dto.chapterId,
				dto.bookId,
			);

		if (!isOwnershipValid) {
			throw new NotFoundException('Page not found or ownership mismatch');
		}

		// Verifica se já está salvo (inclusive deletado)
		const existing = await this.savedPagesRepository.findOneByPageAndUser(
			dto.pageId,
			userId,
			true,
		);

		if (existing) {
			if (existing.isDeleted()) {
				// Restore se estava deletado
				existing.restoreDeleted(
					dto.comment || null,
					dto.isPublic ?? false,
				);
				const saved = await this.savedPagesRepository.save(existing);
				return this.userResourcesMapper.toSavedPage(saved);
			}
			throw new BadRequestException('Page is already saved');
		}

		const savedPage = SavedPage.create(
			'', // ID is generated by DB
			userId,
			dto.pageId,
			dto.chapterId,
			dto.bookId,
			dto.comment || null,
			dto.isPublic ?? false,
		);

		const saved = await this.savedPagesRepository.save(savedPage);
		return this.userResourcesMapper.toSavedPage(saved);
	}

	/**
	 * Lista todas as páginas salvas do usuário
	 */
	async getSavedPages(userIdStr: string): Promise<SavedPageSnapshot[]> {
		const userId = UserId.create(userIdStr);
		const savedPages = await this.savedPagesRepository.findByUser(userId);
		return this.userResourcesMapper.toSavedPageList(savedPages);
	}

	async getPublicSavedPages(userIdStr: string): Promise<SavedPageSnapshot[]> {
		const userId = UserId.create(userIdStr);
		const savedPages =
			await this.savedPagesRepository.findPublicByUser(userId);
		return this.userResourcesMapper.toSavedPageList(savedPages);
	}

	async getPublicSavedPagesByBook(
		userIdStr: string,
		bookId: string,
	): Promise<SavedPageSnapshot[]> {
		const userId = UserId.create(userIdStr);
		const savedPages =
			await this.savedPagesRepository.findPublicByBookAndUser(
				userId,
				bookId,
			);
		return this.userResourcesMapper.toSavedPageList(savedPages);
	}

	/**
	 * Lista páginas salvas por livro
	 */
	async getSavedPagesByBook(
		userIdStr: string,
		bookId: string,
	): Promise<SavedPageSnapshot[]> {
		const userId = UserId.create(userIdStr);
		const savedPages = await this.savedPagesRepository.findByBookAndUser(
			userId,
			bookId,
		);
		return this.userResourcesMapper.toSavedPageList(savedPages);
	}

	/**
	 * Lista páginas salvas por capítulo
	 */
	async getSavedPagesByChapter(
		userIdStr: string,
		chapterId: string,
	): Promise<SavedPageSnapshot[]> {
		const userId = UserId.create(userIdStr);
		const savedPages = await this.savedPagesRepository.findByChapterAndUser(
			userId,
			chapterId,
		);
		return this.userResourcesMapper.toSavedPageList(savedPages);
	}

	/**
	 * Busca uma página salva específica
	 */
	async getSavedPage(
		id: string,
		userIdStr: string,
	): Promise<SavedPageSnapshot> {
		const userId = UserId.create(userIdStr);
		const savedPage = await this.savedPagesRepository.findByIdAndUser(
			id,
			userId,
		);

		if (!savedPage) {
			throw new NotFoundException('Saved page not found');
		}

		return this.userResourcesMapper.toSavedPage(savedPage);
	}

	/**
	 * Verifica se uma página está salva
	 */
	async isPageSaved(pageId: number, userIdStr: string): Promise<boolean> {
		const userId = UserId.create(userIdStr);
		const count = await this.savedPagesRepository.countByPageAndUser(
			pageId,
			userId,
		);
		return count > 0;
	}

	/**
	 * Atualiza o comentário de uma página salva
	 */
	async updateComment(
		id: string,
		dto: UpdateSavedPageDto,
		userIdStr: string,
	): Promise<SavedPageSnapshot> {
		const userId = UserId.create(userIdStr);
		const savedPage = await this.savedPagesRepository.findByIdAndUser(
			id,
			userId,
		);

		if (!savedPage) {
			throw new NotFoundException('Saved page not found');
		}

		savedPage.updateComment(dto.comment ?? null);

		if (dto.isPublic !== undefined) {
			savedPage.updateVisibility(dto.isPublic);
		}

		const saved = await this.savedPagesRepository.save(savedPage);
		return this.userResourcesMapper.toSavedPage(saved);
	}

	async updateVisibility(
		id: string,
		isPublic: boolean,
		userIdStr: string,
	): Promise<SavedPageSnapshot> {
		const userId = UserId.create(userIdStr);
		const savedPage = await this.savedPagesRepository.findByIdAndUser(
			id,
			userId,
		);

		if (!savedPage) {
			throw new NotFoundException('Saved page not found');
		}

		savedPage.updateVisibility(isPublic);
		const saved = await this.savedPagesRepository.save(savedPage);
		return this.userResourcesMapper.toSavedPage(saved);
	}

	/**
	 * Remove uma página salva
	 */
	async unsavePage(id: string, userIdStr: string): Promise<void> {
		const userId = UserId.create(userIdStr);
		const savedPage = await this.savedPagesRepository.findByIdAndUser(
			id,
			userId,
		);

		if (!savedPage) {
			throw new NotFoundException('Saved page not found');
		}

		await this.savedPagesRepository.softRemove(savedPage);
	}

	/**
	 * Remove página salva por pageId (alternativo)
	 */
	async unsavePageByPageId(pageId: number, userId: UserId): Promise<void> {
		const savedPage = await this.savedPagesRepository.findOneByPageAndUser(
			pageId,
			userId,
		);

		if (!savedPage) {
			throw new NotFoundException('Saved page not found');
		}

		await this.savedPagesRepository.softRemove(savedPage);
	}

	/**
	 * Lists saved pages for sync, optionally filtering by lastSyncAt and including soft-deleted records.
	 */
	async getSavedPagesForSync(
		userId: UserId,
		lastSyncAt?: Date,
	): Promise<SavedPage[]> {
		return this.savedPagesRepository.findForSync(userId, lastSyncAt);
	}

	/**
	 * Conta páginas salvas por livro
	 */
	async countSavedPagesByBook(
		userIdStr: string,
		bookId: string,
	): Promise<number> {
		const userId = UserId.create(userIdStr);
		return this.savedPagesRepository.countByBookAndUser(userId, bookId);
	}
}
