# Legacy NanoMQ Config (v0.19 HTTP Auth Bug Fix)
mqtt.property_size = 32
mqtt.max_packet_size = 10MB
mqtt.max_mqueue_len = 2048
mqtt.retry_interval = 10s
mqtt.keepalive_multiplier = 1.25

listeners.tcp.bind = "0.0.0.0:1883"
listeners.ws.bind = "0.0.0.0:8083/mqtt"

log.to = console
log.level = debug

auth.allow_anonymous = false
auth.no_match = deny
auth.deny_action = ignore

auth.http.auth_req.url = http://api:3000/api/auth/mqtt/connect
auth.http.auth_req.method = POST
auth.http.auth_req.headers.content-type = application/json
auth.http.auth_req.params = clientid=%c,username=%u,password=%p

auth.http.super_req.url = http://api:3000/api/auth/mqtt/connect
auth.http.super_req.method = POST
auth.http.super_req.headers.content-type = application/json
auth.http.super_req.params = clientid=%c,username=%u,password=%p

auth.http.acl_req.url = http://api:3000/api/auth/mqtt/acl
auth.http.acl_req.method = POST
auth.http.acl_req.headers.content-type = application/json
auth.http.acl_req.params = clientid=%c,username=%u,password=%p,access=%A,topic=%t
